/**
 * Curated Naukri-spaced preference labels + local autocomplete helpers.
 * Display names keep spaces/punctuation that match Naukri filter/skill chips.
 * Sourced from Naukri Pulse recruiter-searched skills, LinkedIn Jobs on the Rise
 * India 2025, and common India job-board title/keyword searches.
 */

export const TITLE_SUGGESTIONS: readonly string[] = [
  'Software Engineer',
  'Software Developer',
  'Senior Software Engineer',
  'Junior Software Engineer',
  'Full Stack Developer',
  'Full Stack Engineer',
  'Frontend Developer',
  'Frontend Engineer',
  'Backend Developer',
  'Backend Engineer',
  'Java Developer',
  'Java Full Stack Developer',
  'Python Developer',
  'Python Full Stack Developer',
  'React Developer',
  'React.js Developer',
  'Node.js Developer',
  'Angular Developer',
  'Dot Net Developer',
  '.NET Developer',
  'Android Developer',
  'iOS Developer',
  'Mobile App Developer',
  'DevOps Engineer',
  'SRE Engineer',
  'Cloud Engineer',
  'AWS Developer',
  'Data Engineer',
  'Data Scientist',
  'Data Analyst',
  'Machine Learning Engineer',
  'AI Engineer',
  'QA Engineer',
  'SDET',
  'Test Engineer',
  'Automation Test Engineer',
  'Business Analyst',
  'Product Manager',
  'Project Manager',
  'Technical Lead',
  'Tech Lead',
  'Engineering Manager',
  'UI Developer',
  'UI UX Designer',
  'UX Designer',
  'System Engineer',
  'Associate Software Engineer',
  'Graduate Engineer Trainee',
  'Software Development Engineer',
  'SDE',
  'SDE 1',
  'SDE 2',
  'Platform Engineer',
  'Security Engineer',
  'Database Administrator',
  'SQL Developer',
  'ETL Developer',
  'Salesforce Developer',
  'SAP Consultant',
  'Support Engineer',
  'Application Support Engineer',
  'AI ML Engineer',
  'GenAI Engineer',
  'LLM Engineer',
  'MLOps Engineer',
  'Prompt Engineer',
  'Artificial Intelligence Engineer',
  'Deep Learning Engineer',
  'Computer Vision Engineer',
  'NLP Engineer',
  'Search Engineer',
  'Data Architect',
  'Analytics Engineer',
  'BI Developer',
  'Business Intelligence Analyst',
  'Power BI Developer',
  'Tableau Developer',
  'Big Data Engineer',
  'Big Data Architect',
  'Snowflake Developer',
  'Databricks Engineer',
  'Azure Data Engineer',
  'AWS Data Engineer',
  'Cloud Architect',
  'AWS Solutions Architect',
  'Azure Solutions Architect',
  'GCP Cloud Engineer',
  'AWS DevOps Engineer',
  'Azure DevOps Engineer',
  'GCP DevOps Engineer',
  'Site Reliability Engineer',
  'DevSecOps Engineer',
  'Kubernetes Engineer',
  'Terraform Engineer',
  'Infrastructure Engineer',
  'Network Engineer',
  'System Administrator',
  'Systems Engineer',
  'Cybersecurity Analyst',
  'Cyber Security Engineer',
  'Information Security Analyst',
  'Cloud Security Engineer',
  'Application Security Engineer',
  'Penetration Tester',
  'Ethical Hacker',
  'SOC Analyst',
  'Security Architect',
  'Blockchain Developer',
  'Solidity Developer',
  'Web3 Developer',
  'Flutter Developer',
  'React Native Developer',
  'Kotlin Developer',
  'Swift Developer',
  'PHP Developer',
  'Laravel Developer',
  'Ruby on Rails Developer',
  'Go Developer',
  'Golang Developer',
  'C++ Developer',
  'C# Developer',
  'Scala Developer',
  'Rust Developer',
  'Perl Developer',
  'MuleSoft Developer',
  'ServiceNow Developer',
  'SharePoint Developer',
  'WordPress Developer',
  'Web Developer',
  'MERN Stack Developer',
  'MEAN Stack Developer',
  'JavaScript Developer',
  'TypeScript Developer',
  'Next.js Developer',
  'Vue.js Developer',
  'UI Engineer',
  'UX Researcher',
  'Product Designer',
  'Graphic Designer',
  'Visual Designer',
  'Solutions Architect',
  'Software Architect',
  'Enterprise Architect',
  'Technical Architect',
  'Principal Software Engineer',
  'Staff Software Engineer',
  'Lead Software Engineer',
  'Team Lead',
  'Engineering Lead',
  'Delivery Manager',
  'Program Manager',
  'Scrum Master',
  'Agile Coach',
  'Product Owner',
  'Technical Product Manager',
  'Associate Product Manager',
  'Growth Product Manager',
  'IT Project Manager',
  'Technical Project Manager',
  'Quality Analyst',
  'Manual Test Engineer',
  'Performance Test Engineer',
  'QA Lead',
  'Test Lead',
  'Automation Engineer',
  'Selenium Tester',
  'API Test Engineer',
  'Production Support Engineer',
  'L1 Support Engineer',
  'L2 Support Engineer',
  'L3 Support Engineer',
  'IT Support Engineer',
  'Helpdesk Engineer',
  'Desktop Support Engineer',
  'NOC Engineer',
  'Database Developer',
  'Oracle Developer',
  'PL SQL Developer',
  'SQL Server Developer',
  'DBA',
  'Oracle DBA',
  'MySQL DBA',
  'MongoDB Developer',
  'Informatica Developer',
  'Talend Developer',
  'SSIS Developer',
  'Ab Initio Developer',
  'Data Warehouse Developer',
  'SAP ABAP Developer',
  'SAP FICO Consultant',
  'SAP MM Consultant',
  'SAP SD Consultant',
  'SAP Basis Consultant',
  'SAP HANA Consultant',
  'SAP UI5 Developer',
  'SuccessFactors Consultant',
  'Salesforce Administrator',
  'Salesforce Consultant',
  'Apex Developer',
  'Lightning Developer',
  'Workday Consultant',
  'Oracle Cloud Consultant',
  'Dynamics 365 Developer',
  'Power Platform Developer',
  'RPA Developer',
  'UiPath Developer',
  'Automation Anywhere Developer',
  'Blue Prism Developer',
  'Embedded Software Engineer',
  'Firmware Engineer',
  'IoT Engineer',
  'Hardware Engineer',
  'VLSI Engineer',
  'ASIC Design Engineer',
  'FPGA Engineer',
  'Electronics Engineer',
  'Electrical Engineer',
  'Mechanical Engineer',
  'Civil Engineer',
  'BIM Technician',
  'BIM Engineer',
  'Design Engineer',
  'CAD Engineer',
  'Quality Engineer',
  'Manufacturing Engineer',
  'Production Engineer',
  'Process Engineer',
  'Industrial Engineer',
  'Automotive Engineer',
  'Aircraft Maintenance Engineer',
  'Robotics Engineer',
  'Robotics Specialist',
  'Power System Engineer',
  'Instrumentation Engineer',
  'Piping Engineer',
  'Digital Marketing Manager',
  'Digital Marketing Executive',
  'SEO Specialist',
  'SEO Manager',
  'SEM Specialist',
  'PPC Specialist',
  'Content Writer',
  'Content Strategist',
  'Content Manager',
  'Social Media Manager',
  'Social Media Marketing Specialist',
  'Influencer Marketing Specialist',
  'Growth Hacker',
  'Growth Manager',
  'Growth Consultant',
  'Performance Marketing Manager',
  'Brand Manager',
  'Trade Marketing Specialist',
  'Media Buyer',
  'Creative Strategist',
  'Marketing Analyst',
  'Marketing Manager',
  'Email Marketing Specialist',
  'CRM Executive',
  'Business Development Executive',
  'Business Development Manager',
  'Sales Executive',
  'Sales Manager',
  'Inside Sales Executive',
  'Account Executive',
  'Account Manager',
  'Key Account Manager',
  'Customer Success Manager',
  'Client Relationship Manager',
  'Pre Sales Consultant',
  'Solution Consultant',
  'Technical Sales Engineer',
  'HR Executive',
  'HR Manager',
  'HR Business Partner',
  'Talent Acquisition Specialist',
  'Recruiter',
  'Technical Recruiter',
  'Payroll Executive',
  'HR Generalist',
  'Operations Manager',
  'Operations Executive',
  'Operations Analyst',
  'Process Associate',
  'Finance Analyst',
  'Financial Analyst',
  'Accountant',
  'Chartered Accountant',
  'Investment Banking Analyst',
  'Equity Research Analyst',
  'Risk Analyst',
  'Credit Analyst',
  'Compliance Analyst',
  'Audit Associate',
  'Tax Consultant',
  'Company Secretary',
  'Management Consultant',
  'Strategy Consultant',
  'Business Consultant',
  'Management Trainee',
  'Customer Support Executive',
  'Customer Service Representative',
  'Chat Support Executive',
  'Voice Process Executive',
  'BPO Executive',
  'Team Leader BPO',
  'Nurse',
  'Registered Nurse',
  'Pharmacist',
  'Medical Coder',
  'Clinical Research Associate',
  'Behavioral Therapist',
  'School Counsellor',
  'Physiotherapist',
  'Travel Specialist',
  'Travel Consultant',
  'Food and Beverage Manager',
  'Cafe Manager',
  'Hotel Manager',
  'Restaurant Manager',
  'Closing Manager',
  'Real Estate Manager',
  'Sustainability Analyst',
  'Sustainability Consultant',
  'ESG Analyst',
  'Legal Associate',
  'Corporate Lawyer',
  'Paralegal',
  'Company Legal Counsel',
  'Teacher',
  'Lecturer',
  'Corporate Trainer',
  'Instructional Designer',
  'Research Analyst',
  'Market Research Analyst',
  'Operations Research Analyst',
  'Supply Chain Analyst',
  'Logistics Manager',
  'Procurement Manager',
  'Purchase Executive',
  'Warehouse Manager',
  'Inventory Manager',
  'Category Manager',
  'Fresher',
  'Intern',
  'Graduate Trainee',
  'Junior Developer',
  'Junior Data Analyst',
  'Junior Data Scientist',
  'Associate Consultant',
  'Senior Consultant',
  'Lead Consultant',
  'Principal Consultant',
  'Vice President Engineering',
  'Director of Engineering',
  'CTO',
  'CIO',
  'Head of Engineering',
  'Head of Product',
  'VP Product',
  'Application Developer',
  'Application Tech Support Practitioner',
  'IT Architect',
  'Integration Developer',
  'API Developer',
  'Microservices Developer',
  'Middleware Developer',
  'Mainframe Developer',
  'Cobol Developer',
  'PEGA Developer',
  'OutSystems Developer',
  'Low Code Developer',
  'Mendix Developer',
  'PowerApps Developer',
  'Unreal Engine Developer',
  'Unity Developer',
  'Game Developer',
  'AR VR Developer',
  'QA Automation Engineer',
  'Release Engineer',
  'Build and Release Engineer',
  'Configuration Manager',
  'Change Manager',
  'Incident Manager',
  'Problem Manager',
  'ITIL Consultant',
  'Service Desk Analyst',
  'Technical Writer',
  'Documentation Specialist',
  'BI Analyst',
  'Reporting Analyst',
  'MIS Executive',
  'Excel Specialist',
  'SAS Developer',
  'SPSS Analyst',
  'Statistician',
  'Quantitative Analyst',
  'Actuarial Analyst',
  'Underwriter',
  'Claims Analyst',
  'Telecom Engineer',
  'RF Engineer',
  'Network Security Engineer',
  'Wireless Engineer',
  'Voice Engineer',
  'UC Engineer',
  'Collaboration Engineer',
  'Oracle EBS Consultant',
  'PeopleSoft Developer',
  'Workday HCM Consultant',
  'Coupa Consultant',
  'Anaplan Consultant',
  'Adobe Experience Manager Developer',
  'Sitecore Developer',
  'Drupal Developer',
  'Magento Developer',
  'Shopify Developer',
  'E Commerce Manager',
  'Product Analyst',
  'Business Systems Analyst',
  'Functional Analyst',
  'System Analyst',
  'Requirements Analyst',
  'Process Analyst',
  'Lean Six Sigma Consultant',
  'Implementation Consultant',
  'Onboarding Specialist',
  'Customer Experience Manager',
  'Community Manager',
  'Partnership Manager',
  'Affiliate Marketing Manager',
  'PR Executive',
  'Communications Manager',
  'Event Manager',
  'Video Editor',
  'Motion Graphic Designer',
  '3D Artist',
  'Animator',
  'Photographer',
  'Videographer',
  'Senior Data Engineer',
  'Senior Data Scientist',
  'Senior Data Analyst',
  'Senior DevOps Engineer',
  'Senior Cloud Engineer',
  'Senior Frontend Developer',
  'Senior Backend Developer',
  'Senior Full Stack Developer',
  'Senior Java Developer',
  'Senior Python Developer',
  'Senior React Developer',
  'Senior Android Developer',
  'Senior iOS Developer',
  'Senior QA Engineer',
  'Senior Business Analyst',
  'Senior Product Manager',
  'Lead Data Engineer',
  'Lead Data Scientist',
  'Lead DevOps Engineer',
  'Lead QA Engineer',
  'Lead Java Developer',
  'Lead Python Developer',
  'Lead Frontend Engineer',
  'Junior Software Developer',
  'Junior Frontend Developer',
  'Junior Backend Developer',
  'Junior QA Engineer',
  'Junior Business Analyst',
  'Trainee Software Engineer',
  'Intern Software Engineer',
  'Campus Hire',
  'Software Engineer Intern',
  'Member of Technical Staff',
  'MTS',
  'Principal Engineer',
  'Distinguished Engineer',
  'Architect',
  'Solution Engineer',
  'Customer Engineer',
  'Forward Deployed Engineer',
  'Developer Advocate',
  'Developer Relations Engineer',
  'Technical Evangelist',
  'Release Manager',
  'Environment Manager',
  'Capacity Planner',
  'Data Steward',
  'Data Governance Analyst',
  'Master Data Management Specialist',
  'Privacy Analyst',
  'Data Protection Officer',
  'AI Ethics Specialist',
  'AI Product Manager',
  'ML Product Manager',
  'Data Product Manager',
  'Platform Product Manager',
  'API Product Manager',
  'Trust and Safety Analyst',
  'Content Moderator',
  'Fraud Analyst',
  'KYC Analyst',
  'AML Analyst',
  'Transaction Monitoring Analyst',
  'Wealth Manager',
  'Relationship Manager',
  'Branch Manager',
  'Loan Officer',
  'Insurance Advisor',
  'Actuary',
  'Claims Manager',
  'Store Manager',
  'Retail Manager',
  'Merchandiser',
  'Visual Merchandiser',
  'Fashion Designer',
  'Interior Designer',
  'Architect Civil',
  'Quantity Surveyor',
  'Site Engineer',
  'Construction Manager',
  'Project Engineer',
  'HSE Officer',
  'Safety Officer',
  'Quality Control Engineer',
  'Quality Assurance Manager',
  'Lab Technician',
  'Chemist',
  'Biotechnologist',
  'Microbiologist',
  'Clinical Data Manager',
  'Pharmacovigilance Associate',
  'Medical Writer',
  'Radiologist Technician',
  'Lab Assistant',
  'Cabin Crew',
  'Airport Operations Executive',
  'Ground Staff',
  'Fleet Manager',
  'Driver Coordinator',
  'Journalist',
  'Editor',
  'Copywriter',
  'Proofreader',
  'Translator',
  'Librarian',
  'Research Associate',
  'Policy Analyst',
  'NGO Program Manager',
  'Fundraising Manager',
  'Development Officer',
  'Public Policy Associate',
  'Government Affairs Manager',
];

export const KEYWORD_SUGGESTIONS: readonly string[] = [
  'Java',
  'Spring',
  'Spring Boot',
  'Spring MVC',
  'Spring Security',
  'Spring Batch',
  'Spring Integration',
  'Hibernate',
  'JPA',
  'Microservices',
  'REST',
  'REST API',
  'GraphQL',
  'JavaScript',
  'TypeScript',
  'React.js',
  'React Native',
  'Next.js',
  'Node.js',
  'Express.js',
  'Angular',
  'Vue.js',
  'HTML',
  'CSS',
  'SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Kafka',
  'RabbitMQ',
  'Docker',
  'Kubernetes',
  'AWS',
  'Amazon Web Services',
  'Google Cloud Platform',
  'Azure',
  'CI/CD',
  'Jenkins',
  'Git',
  'GitHub',
  'GitLab',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'C#',
  '.NET',
  '.NET Core',
  'ASP.NET',
  'C++',
  'Go',
  'Golang',
  'Kotlin',
  'Swift',
  'Android',
  'iOS',
  'Selenium',
  'Cypress',
  'Playwright',
  'JUnit',
  'TestNG',
  'Agile',
  'Scrum',
  'Jira',
  'Linux',
  'Unix',
  'Shell Scripting',
  'Data Structures',
  'Algorithms',
  'System Design',
  'Object Oriented Programming',
  'OOP',
  'Design Patterns',
  'Machine Learning',
  'Deep Learning',
  'Artificial Intelligence',
  'NLP',
  'TensorFlow',
  'PyTorch',
  'Power BI',
  'Tableau',
  'ETL',
  'Data Warehousing',
  'Snowflake',
  'Spark',
  'Hadoop',
  'Salesforce',
  'SAP',
  'Oracle',
  'PL/SQL',
  'API Testing',
  'Manual Testing',
  'Automation Testing',
  'Communication Skills',
  'Problem Solving',
  '.NET Framework',
  'Active Directory',
  'ADO.NET',
  'Adobe XD',
  'Airflow',
  'Ajax',
  'AKS',
  'Android Development',
  'AngularJS',
  'Ansible',
  'Apache Airflow',
  'Apex',
  'API',
  'Appium',
  'ArgoCD',
  'AS400',
  'ASP.NET MVC',
  'AutoCAD',
  'Automation Anywhere',
  'AWS Lambda',
  'Azure Data Factory',
  'Azure Data Lake',
  'Azure Databricks',
  'Azure DevOps',
  'Azure ML',
  'Azure Synapse',
  'Bamboo',
  'Bash Scripting',
  'BDD',
  'Big Data',
  'BigQuery',
  'BIM',
  'Bitbucket',
  'Black Box Testing',
  'Blockchain',
  'Blue Prism',
  'Bootstrap',
  'Business Analysis',
  'Business Intelligence',
  'Cassandra',
  'Cloud Computing',
  'Cloud Security',
  'Cloudera',
  'CNN',
  'COBOL',
  'CodeIgniter',
  'Computer Vision',
  'Confluence',
  'Containerization',
  'Core Java',
  'CRM',
  'CSS3',
  'Cucumber',
  'Cybersecurity',
  'Data Engineering',
  'Data Modeling',
  'Data Science',
  'Data Visualization',
  'Database Testing',
  'Databricks',
  'Datadog',
  'DAX',
  'DB2',
  'dbt',
  'DevOps',
  'Drupal',
  'Dynamics 365',
  'DynamoDB',
  'EC2',
  'EKS',
  'Elasticsearch',
  'ELK',
  'Embedded C',
  'Entity Framework',
  'ERP',
  'ES6',
  'Ethical Hacking',
  'Excel',
  'Figma',
  'Firebase',
  'Firewall',
  'Flutter',
  'GCP',
  'GenAI',
  'Generative AI',
  'GitHub Actions',
  'GitOps',
  'GKE',
  'Google Ads',
  'Google Analytics',
  'Gradle',
  'Grafana',
  'gRPC',
  'HDFS',
  'Helm',
  'Hive',
  'HTML5',
  'Hugging Face',
  'IAM',
  'Illustrator',
  'Informatica',
  'Infrastructure as Code',
  'Integration Testing',
  'Ionic',
  'iOS Development',
  'IoT',
  'ITIL',
  'J2EE',
  'Java 8',
  'Java Web Services',
  'Jest',
  'Jetpack Compose',
  'JMeter',
  'jQuery',
  'JSON',
  'JWT',
  'Kanban',
  'Keras',
  'Lambda',
  'LangChain',
  'Laravel',
  'LINQ',
  'LLM',
  'Load Testing',
  'LoadRunner',
  'Looker',
  'Magento',
  'Mainframes',
  'MapReduce',
  'Marketing Cloud',
  'MATLAB',
  'Matplotlib',
  'Maven',
  'MEAN Stack',
  'MERN Stack',
  'MLOps',
  'Mockito',
  'MS Excel',
  'MS Office',
  'MS PowerPoint',
  'MS SQL',
  'MuleSoft',
  'MVC',
  'Neo4j',
  'NestJS',
  'Network Security',
  'New Relic',
  'Nginx',
  'NLTK',
  'NoSQL',
  'NumPy',
  'Nuxt.js',
  'OAuth',
  'OpenAPI',
  'OpenCV',
  'OpenShift',
  'Oracle SQL',
  'Pandas',
  'PEGA',
  'Penetration Testing',
  'Performance Testing',
  'Perl',
  'Photoshop',
  'PHP',
  'PLC',
  'Plotly',
  'PMP',
  'Postman',
  'Power Query',
  'PowerApps',
  'PowerShell',
  'PPC',
  'Prisma',
  'Project Management',
  'Prometheus',
  'Prompt Engineering',
  'Puppet',
  'Pytest',
  'QA Automation',
  'Qlik',
  'RAG',
  'RDBMS',
  'Redshift',
  'Redux',
  'Regression Testing',
  'Requirement Gathering',
  'Responsive Web Design',
  'RESTful Web Services',
  'Revit',
  'RHEL',
  'RNN',
  'Robot Framework',
  'RPA',
  'Ruby',
  'S/4HANA',
  'S3',
  'SAFe',
  'SageMaker',
  'Sales Cloud',
  'Salesforce Aura',
  'Salesforce LWC',
  'SAP ABAP',
  'SAP Basis',
  'SAP FICO',
  'SAP HANA',
  'SAP MM',
  'SAP SD',
  'SAPUI5',
  'Sass',
  'SCADA',
  'Scala',
  'Scikit-learn',
  'Seaborn',
  'Selenium WebDriver',
  'SEM',
  'SEO',
  'Service Cloud',
  'ServiceNow',
  'Servlets',
  'SharePoint',
  'SIEM',
  'Six Sigma',
  'SOAP',
  'SoapUI',
  'Solidity',
  'SolidWorks',
  'Solr',
  'SonarQube',
  'SpaCy',
  'Splunk',
  'Spring Cloud',
  'SQL Server',
  'SQLAlchemy',
  'SSIS',
  'SSRS',
  'Stakeholder Management',
  'Streamlit',
  'Struts',
  'SuccessFactors',
  'Swagger',
  'SwiftUI',
  'T-SQL',
  'Tally',
  'Terraform',
  'Tomcat',
  'TypeORM',
  'UI Automation',
  'UI Development',
  'UiPath',
  'Unit Testing',
  'Unity',
  'Unreal Engine',
  'VB.NET',
  'Vertex AI',
  'Visualforce',
  'VMware',
  'VPN',
  'Vulnerability Assessment',
  'WCF',
  'Web API',
  'Web Development',
  'Windows Server',
  'WordPress',
  'Workday',
  'Xamarin',
  'XML',
];

export const LOCATION_SUGGESTIONS: readonly string[] = [
  'Hyderabad',
  'Hyderabad/Secunderabad',
  'Bengaluru',
  'Bangalore',
  'Bengaluru/Bangalore',
  'Chennai',
  'Mumbai',
  'Pune',
  'Delhi',
  'Delhi/NCR',
  'Noida',
  'Gurgaon',
  'Gurugram',
  'Kolkata',
  'Ahmedabad',
  'Jaipur',
  'Chandigarh',
  'Kochi',
  'Coimbatore',
  'Indore',
  'Nagpur',
  'Thiruvananthapuram',
  'Visakhapatnam',
  'Mysore',
  'Remote',
  'Work From Home',
];

/** Lowercase alphanumeric compact form: "Spring Boot" → "springboot". */
export function compactMatchText(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9+#]/g, '');
}

/** Spaced normalize for display/search compare: punctuation → spaces. */
export function normalizePreferenceText(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9+#.]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Resolve a draft to a catalog label (case/spacing insensitive).
 * Unknown free-text is rejected — returns '' so chips stay Naukri-valid.
 */
export function canonicalizePreferenceValue(
  raw: string,
  catalog: readonly string[]
): string {
  const trimmed = raw.trim();
  if (!trimmed) return '';
  const compact = compactMatchText(trimmed);
  if (!compact) return '';
  const exact = catalog.find(
    (item) => compactMatchText(item) === compact
  );
  return exact ?? '';
}

export type SuggestPreferenceOptions = {
  /** Already-selected values to exclude (case-insensitive). */
  exclude?: readonly string[];
  limit?: number;
};

/**
 * Local autocomplete against a curated catalog.
 * Matches prefix on spaced or compact forms (e.g. "sprin" → "Spring Boot").
 */
export function suggestPreferenceValues(
  query: string,
  catalog: readonly string[],
  options: SuggestPreferenceOptions = {}
): string[] {
  const limit = options.limit ?? 8;
  const q = query.trim().toLowerCase();
  const qCompact = compactMatchText(query);
  const excluded = new Set(
    (options.exclude ?? []).map((v) => v.toLowerCase())
  );

  if (!q && !qCompact) {
    return catalog
      .filter((item) => !excluded.has(item.toLowerCase()))
      .slice(0, limit);
  }

  const scored: { item: string; score: number }[] = [];
  for (const item of catalog) {
    if (excluded.has(item.toLowerCase())) continue;
    const lower = item.toLowerCase();
    const compact = compactMatchText(item);
    let score = -1;
    if (lower.startsWith(q)) score = 100 - lower.length;
    else if (compact.startsWith(qCompact)) score = 80 - compact.length;
    else if (lower.includes(q)) score = 60 - lower.indexOf(q);
    else if (qCompact.length >= 2 && compact.includes(qCompact)) {
      score = 40 - compact.indexOf(qCompact);
    }
    if (score >= 0) scored.push({ item, score });
  }

  scored.sort((a, b) => b.score - a.score || a.item.localeCompare(b.item));
  return scored.slice(0, limit).map((s) => s.item);
}
